# Algorithms
Textbook: Introduction to Algorithms <br>
Author: Thomas Cormen ..


In [9]:
import numpy as np

# Part II Sorting Algorithms

## Comparison Sorts
the sorted order they determine
is based only on comparisons between the input elements.

## Insertion Sort|

In [10]:
def insertion_sort(A):
    # This is a sorting technique wh|ich is efficient for small amounts of numbers
    # it takes in an array A[a1 , a2 , ... an]
    # The sorting is done in place.
    num = len(A)
    for j in range(1 , num):
        key = A[j]      # gets the value at the loc of j
        i = j-1                 # the last position of the sorted array
        while i >= 0 and A[i] > key:
            A[i + 1] = A[i]
            i = i-1 
        A[i + 1] = key

# Test the program
x = np.array([2,3,1,0])
insertion_sort(x)
x

array([0, 1, 2, 3])

Insertion sort has a quadratic running time, thus is ineficient as the scale of the imput increses. <br>
<br>
Insertion sort uses an incrimental approach. 

### Exercise 2.1-3
Consider the searching problem: <br>
Input: A sequence of n numbers A = a1, a2, . . . , an and a value v. <br>
Output: An index i such that v = A[i ] or the special value NIL if v does not
appear in A. <br> <br>
    Write pseudocode for linear search, which scans through the sequence, looking
for v. Using a loop invariant, prove that your algorithm is correct. Make sure that
your loop invariant fulfills the three necessary properties.

In [11]:
def linear_search(A , v):
    # The input: A is a 1D array of numbers. v is your target item
    num = len(A)
    locations = []
    for j in range( num):
        if v == A[j]:               # check at this location
            locations += [j]
    if locations ==[]:
        return None
    else:
        return locations
    
# Test the program
x = np.array([2,3,1,2])
linear_search(x , 2)

[0, 3]

## Merge Sort

In [12]:
def merge(A , p , q , r):
    # This requires that the two subsets are fully sorted
    # here, A is the array of numbers, p, q , r are indices, p <= q < r
    # The subarray will be as follows in indices: [p ... q | ... r]
    
    n1 = q - p +1
    n2 = r -q

    # Create the L and R arrays according to the split defined by q
    # add an aditional space for the sentinel
    L = np.zeros([n1 + 1])
    R = np.zeros([n2 + 1])
    
    # fill those arrays with the values in A
    for i in range(0 , n1): 
        L[i] = A[p + i] 
  
    for j in range(0 , n2): 
        R[j] = A[q + 1 + j] 
    
    # add the sentinal
    L[-1] = np.inf
    R[-1] = np.inf
    
    # set
    i = 0
    j = 0
    
    for k in range(p , r + 1):
        if L[i] <= R[j]:
            A[k] = L[i]
            i += 1
        else:
            A[k] = R[j]
            j += 1


# Test it out and make sure it is working properly.

x = np.array([2 , 4 , 5 , 7 , 1 , 2 , 3 , 6 ,8 , 10])
merge(x , 0 , 3 , 5)
x



array([ 1,  2,  2,  4,  5,  7,  3,  6,  8, 10])

In [13]:

def merge_sort(A , p , r):
    # This program sorts an array or subarray.
    # The subarray will be as follows in indices: [p ... q | ... r]
    # we first split until every split is sorted (of length one)
    if p < r :    
        q = (p + r )//2  
  
        # Sort first and second halves 
        merge_sort(A, p, q)                 # use recursion 
        merge_sort(A, q + 1 , r) 
        merge(A, p, q, r)                   # Merge all fully sorted subarrays
        

# Test it out: This will sort the entire array
x = []
for i in range(11):
    val = np.random.randint(0 , 100)
    x += [val]
print("before , " , x)
v = len(x) - 1
merge_sort(x , 0 , v)
print("After , " , x)

before ,  [48, 37, 9, 96, 27, 81, 93, 62, 74, 20, 76]
After ,  [9.0, 20.0, 27.0, 37.0, 48.0, 62.0, 74.0, 76.0, 81.0, 93.0, 96.0]


## Heap Sort

### Heap

In [14]:
class Binary_heap():
    # This class is for a binary heap which maintains two properties
    # The length of the array, and the size of the heap
    # The heap size is less than or equal to the length of the array
    def __init__(self, data , heap_size = None):
        self.array = data
        self.length = len(self.array)
        if heap_size == None:
            self.heap_size = len(self.array)
        else:
            self.heap_size = heap_size
            
    def get_parent(self , index):
        # given the index of an element in the heap
        # This function returns the index of its parent element 
        if index != 0:
            return (index - 1 ) //2 
        else:
            print("Root node has no parent node.")
            return None

    def get_left(self, index):
        # given the index of an element in the heap
        # This function returns the index of the left child node
        return 2 * index + 1
    
    def get_right(self , index):
        # given the index of an element in the heap
        # This function returns the index of the right child node
        return (index + 1) * 2

### Max Heapify
The MAX-HEAPIFY procedure, which runs in O(lg n) time, is the key to maintaining
the max-heap property.

In [15]:
def max_heapify(heap , i):
# This function is important for maintaining the max heap property (parent is greater 
# its children)
# it takes in an Array (binary heap) and the root index for the array
# RIGHT NOW THIS FUNCTION ONLY WORKS IF YOU START AT AN INDEX THAT VIOLATES THE MAX HEAP PROPERTY
    r = heap.get_right(i)
    l = heap.get_left(i)

    heap_size = heap.heap_size
    largest = i
    Arr = heap.array
    
    if l < heap_size and heap.array[l] > heap.array[largest]:    # Check to see if the left side is larger
        largest = l
    
    if r < heap_size and heap.array[r] > heap.array[largest]:    # Check to see if the right side is larger
        largest = r

    if largest != i:  # if you made a change, swap the values , and apply recursion.
        heap.array[i] , heap.array[largest] = heap.array[largest] , heap.array[i]
        max_heapify(heap , largest)
    
    
# Try it out 
x = np.array([10 , 6 , 1 , 4 , 3 , 9 , 8 , 2 , 1 , 1 , 1 , 1 , 1, 1, 9])
heap = Binary_heap(x)
max_heapify(heap, 2)
heap.array

array([10,  6,  9,  4,  3,  1,  8,  2,  1,  1,  1,  1,  1,  1,  9])

### Build Max Heap
The BUILD-MAX-HEAP procedure, which runs in linear time, produces a maxheap
from an unordered input array.

In [16]:
def build_max_heap(heap):
    heap.heap_size = heap.length     # set the heap size to the length of the array
    for i in range(( heap.length //2) -1 , -1 , -1):
        max_heapify(heap , i)
        
# Try it out
x = np.array([4 , 1 , 3 , 2 , 16,  9 , 10 , 14 , 8  , 7]) 
heap = Binary_heap(x)
build_max_heap(heap)
heap.array

array([16, 14, 10,  8,  7,  9,  3,  2,  4,  1])

### Heap Sort
The HEAPSORT procedure, which runs in O(n lg n) time, sorts an array in
place. <dir>
    1. build a max heap
    2. move the largest element (root) to the last position
    3. Shrink the heap size by one
    4. repeat

In [17]:
def heap_sort(heap):
    build_max_heap(heap)                     # build the max heap off of the entire array
    for i in range(heap.length - 1 , 0 , -1):
        heap.array[0] , heap.array[i] = heap.array[i] , heap.array[0]   # exchange first and last elements
        heap.heap_size -= 1       # reduce heap size by one
        max_heapify(heap , 0)
        
# Try it out
x = np.array([5, 13, 2, 25, 7, 17, 20, 8, 4])
heap = Binary_heap(x)
heap_sort(heap)
heap.array

array([ 2,  4,  5,  7,  8, 13, 17, 20, 25])

## Priority QUEUE
Most popular application of a heap <br>
A max priotiry queue has the following procedures which run in O(lg n) time: <dir>
    * INSERT(S, x) inserts the element x into the set S. This operation could be written as S ← S ∪ {x}.
    * MAXIMUM(S) returns the element of S with the largest key.
    * EXTRACT-MAX(S) removes and returns the element of S with the largest key.
    * INCREASE-KEY(S, x, k) increases the value of element x’s key to the new value k, which is assumed to be at least as large as x’s current key value. <br>
    
A min priority queue, often used in an event driven simulator: <dir>
    * INSERT(S, x) 
    * Minimun(S)
    * EXTRACT-Min(S) 
    * DECREASE-KEY(S, x, k) 

In [18]:
def heap_maximun(heap):
    # This returns the first element in an array
    return heap.array[0]

In [19]:
def heap_extract_max(heap):
    if heap.heap_size < 1:       # return an error if the heap size is zero
        error_mess = "heap underflow"   
        return(error_mess)    
    max_val = heap.array[0]              # select the max value
    heap.array[0] = heap.array[-1]       # push the last element to the front
    heap.heap_size -= 1                  # reduce the heap size
    max_heapify(heap , 0)                # rebuild the max heap
    return max_val                       # return the max value

# Try it out
x = np.array([5, 13, 2, 25, 7, 17, 20, 8, 4])
heap = Binary_heap(x)
max_heapify(heap, 0)
val = heap_extract_max(heap)
print(val)
heap.array

13


array([25,  8,  2,  5,  7, 17, 20,  4,  4])

In [20]:
def heap_increase_key(heap , i , key):
# The priority-queue element whose key is to be increased is identified by an
# index i into the array. The procedure first updates the key of element A[i ] to its
# new value.

    if key < heap.array[i]:       # return an error if the new key is smaller
        error_mess = "new key is smaller than current key"  
        return(error_mess)  
    heap.array[i] = key
    while i > 0 and heap.array[heap.get_parent(i)] < heap.array[i]:
        heap.array[i] , heap.array[heap.get_parent(i)] = heap.array[heap.get_parent(i)] , heap.array[i]   # exchange
        i = heap.get_parent(i)
        
        
# Try it out (example 6.5)
x = np.array([16 , 14 , 10 , 8 , 7 , 9 ,3 , 2 , 4 , 1])
heap = Binary_heap(x)
heap_increase_key(heap , 8 , 15)  # replace 4 with 15 and run heap_increase_key
print(heap.array)

[16 15 10 14  7  9  3  2  8  1]


In [21]:
def max_heap_insert(heap , key):
    heap.heap_size += 1      # need to make room for one more element
    heap.length += 1
    heap.array = np.append(heap.array , 0)
    last_element_of_heap = heap.heap_size - 1
    heap.array[last_element_of_heap] = np.NINF     # make last element of heap -inf
    heap_increase_key(heap, last_element_of_heap , key )

# Try it out ( again using the tree from example 6.5)
x = np.array([16 , 14 , 10 , 8 , 7 , 9 ,3 , 2 , 4 , 1] ,dtype = object)
heap = Binary_heap(x)
max_heap_insert(heap , 11)
heap.array

array([16, 14, 10, 8, 11, 9, 3, 2, 4, 1, 7], dtype=object)

## Quicksort
in practice quicksort often outperforms heap sort <br>
* Divide: Partition (rearrange) the array A[p . . r] into two (possibly empty) subarrays
A[p . . q −1] and A[q +1 . . r] such that each element of A[p . . q −1] is
less than or equal to A[q], which is, in turn, less than or equal to each element
of A[q + 1 . . r]. Compute the index q as part of this partitioning procedure.
* Conquer: Sort the two subarrays A[p . . q−1] and A[q +1 . . r] by recursive calls
to quicksort.
* Combine: Since the subarrays are sorted in place, no work is needed to combine
them: the entire array A[p . . r] is now sorted.

#### Partitoning the array

In [22]:
def partition(A , p , r):
    # rearange the subaray A[p . . r] in place.
    # final result [vals < A[p] , A[p] ,  vals > A[p] ]
    x = A[r]
    i = p - 1
    for j in range(p , r): 
        if A[j] <= x:
            i += 1
            A[i] , A[j] = A[j] , A[i]
    A[i +1] , A[r] = A[r] , A[i + 1]
    return(i + 1)

# Try it out       
x = np.array([5, 13, 2, 7 , 25, 17, 20, 8, 4 , 9])
partition(x , 0, 9)
print(x)


[ 5  2  7  8  4  9 20 13 25 17]


In [23]:
def quick_sort(A , p , r ):
# To sort an entire array A, the initial call is QUICKSORT(A, 0, length[A] - 1)
    if p < r:
        q = partition(A , p , r) 
        quick_sort(A, p,  q - 1)
        quick_sort(A, q + 1, r)
        
# Try it out       
x = np.array([5, 13, 2, 7, 25,  17, 20, 8, 4 , 9])
quick_sort(x , 0 , 9)
print(x)

[ 2  4  5  7  8  9 13 17 20 25]


### Randomized Quicksort
we can sometimes add randomization to an algorithm in order to obtain good average-case performance over all inputs. Many people regard the resulting randomized version of quicksort as the sorting algorithm of choice for large enough inputs.


In [24]:
def randomized_partition(A , p , r):
    i = np.random.randint(p , r)
    A[i] , A[r] = A[r] , A[i]
    return partition(A , p , r)

In [25]:
def randomized_quick_sort(A , p , r):
# To sort an entire array A, the initial call is QUICKSORT(A, 0, length[A] - 1)
# only difference from quicksort is the use of randomized_partition
    if p < r:
        q = randomized_partition(A , p , r) 
        randomized_quick_sort(A, p,  q - 1)
        randomized_quick_sort(A, q + 1, r)

# Try it out       
x = np.array([5, 13, 2, 7, 25,  17, 20, 8, 4 , 9])
randomized_quick_sort(x , 0 , 9)
print(x)

[ 2  4  5  7  8  9 13 17 20 25]


## Sorting in Linear Time
These sorting methods will not be comparison based

## Counting Sort
This a stable sorting method which operates in linear time. <br>
Stable:numbers with the same value appear in the output array in the same order as they do in the input array.  <br>
Counting sort is often used as a subroutine in radix sort 

In [55]:
def counting_sort(A  , k):
    # k is the maximum value of A
    B = np.zeros(len(A) , dtype = int)
    C = np.zeros(k+1 ,dtype=int)
    for j in range(0 , len(A) ):
        C[A[j]] = C[A[j]] + 1        # keep track of the instances for each number
        
    for i in range(1 , k+1):
        C[i] = C[i] + C[i - 1]    # C[i] is the number of elements equal to or less than i
    
    for j in range(len(A) - 1 ,-1 , -1):
        B[C[A[j]] - 1] = A[j]
        C[A[j]] = C[A[j]] - 1
    
    return B

# Try it out
x = np.array([2 , 5 , 3 , 0 , 2 , 3 , 0 , 3])

v = counting_sort(x  , 5)
print(v)

[0 0 2 2 3 3 3 5]


### Counting Sort for Radix Subroutine

In [56]:
def counting_sort_subr(A ,k , digit = 1):
    B = np.zeros(len(A) , dtype = int)
    C = np.zeros(k+1 ,dtype=int)
    for j in range(0 , len(A) ):
        num = get_digit(A[j], digit)
        C[num] = C[num] + 1        # keep track of the instances for each number
    for i in range(1 , k+1):
        C[i] = C[i] + C[i - 1]    # C[i] is the number of elements equal to or less than i
    
    for j in range(len(A) - 1 ,-1 , -1):
        num = get_digit(A[j], digit)
        B[C[num] - 1] = A[j]
        C[num] = C[num] - 1
    
    return B


# Try it out
x = np.array([200 , 521 , 313 , 0 , 222 , 113 , 220 , 233])
B = np.zeros(len(x) , dtype = int)

print(counting_sort_subr(x , 9 , 3) )

[  0 113 200 222 220 233 313 521]


## Radix Sort
For now this will only work for integers. If you want to extend this to floating point numbers, you simply need to adjust the get_digit function such that it starts with the digitis past the decimal point

In [28]:
def get_digit(number, n):
    return int(number // 10**(n - 1) % 10 )

def radix_sort(A , d):
    # d is the number of digits for the numbers in the array A
    for i in range(1 , d + 1  ):
        A = counting_sort_subr(A , 9 , i)
    
    return A
# Try it out
x = np.array([200 , 521 , 313 , 0 , 222 , 113 , 220 , 233])

radix_sort(x , 3)


array([  0, 113, 200, 220, 222, 233, 313, 521])

## Bucket Sort

## Medians and Order Statistics

### The selection problem 
* Input: A set A of n (distinct) numbers and a number i , with 1 ≤ i ≤ n.
* Output: The element x ∈ A that is larger than exactly i − 1 other elements of A.

In [29]:
def min_max(arr): 
    # this function takes in an array of numbers and returns the min , max
    minimum = arr[0]
    maximum = arr[0]
    
    # evaluate the elements in pairs. instead of 2 comparisons per element, we do 3 comaparisons for each pair
    for i in range(1 , len(arr) //2 + 1):
        if (2 * i) == len(arr):               # if only one left
            if maximum < arr[2 * i - 1]:    # check max
                maximum = arr[2 * i - 1]
            if minimum > arr[2 * i - 1]:    # check min
                minimum = arr[2 * i - 1]
        else:
            larger = 2 * i - 1
            smaller = 2 * i 
            if arr[i] < arr[i + 1]:      # comparison 1 - items to themselves
                larger = i + 1
                smaller = i

            if maximum < arr[larger]:    # comparison 2 - larger item to maximum
                maximum = arr[larger] 

            if minimum > arr[smaller]:
                minimum = arr[smaller]   # comparison three - smaller item to minimum
    return minimum , maximum

# Try it out
x = np.array([2 , 4 , 6 , 7 , 11 , 4 , 3, 2, 1 , 0])
mi , ma = min_max(x)
print("The minimum and maximum values are: " , mi , " , " , ma)

The minimum and maximum values are:  0  ,  11


## Selection in expected Linear time
The following code for RANDOMIZED-SELECT returns the ith smallest
element of the array A[p . . r]. <dir>
    * it uses the randomized partition method written earlier. 
    * i = 1 corresponds to the smallest element
    * p is the smallest index of the subarray
    * r is the largest INDEX of the subarray (in python this is length - 1 )

In [53]:
def randomized_select(A , p , r , i):
    if p == r:
        return A[p]
    else:
        q = randomized_partition(A , p , r)
        k = q - p + 1
        if i == k:       # the pivot is the answer
            return A[q]
        elif i <k:
            return randomized_select(A, p, q-1, i )
        else:
            return randomized_select(A, q + 1, r, i-k)

        # try it out           
x = np.array([8 , 3 , 3, 4 , 5 ])
el = randomized_select(x , 0 , 4 , 3)
print(el)

4


## Selection in worst-case linear time
#### Select method
The difference is this will guarentee a good partition when the split is made

# Part III Data Structures

## Stacks and Queues
Stacks use the last in first out method <br>
Queues use the first in first out method

In [195]:
class Stack():
    def __init__(self , size = -1): 
        # the stack takes in the maximum Number of elements for the stack array
        # size defaults to  -1 which will never throw error (no limit)
        self.data = np.empty(0)
        self.top = -1
        self.max = size 
        
    
    def stack_empty(self):
        if self.top == -1:
            return True
        else:
            return False
    
    def push(self , item):
        if self.top != self.max - 1:
            self.top += 1
            self.data = np.hstack([self.data, item])
        else:
            err = "stack overflow , push failed"
            print(err)
    
    def pop(self):
        if self.stack_empty():
            err = "stack underflow , pop failed"
            print(err)
            return None
        else:
            self.top -= 1
            element = self.data[self.top + 1]
            self.data = self.data[:-1]
            return element

In [196]:
s = Stack(1)
s.push(1)


In [272]:
class Queue():
    # This queue requires a specified length
    # in has the ability to add and remove elements from the queue while checking for
    # underflow and overflow
    
    def __init__(self, size ):
        # this queue requires that the queue is initialized with a maximum size
        self.data = np.full((size) , None)
        self.head = 0
        self.tail = 0
        self.max = size
        
    def enqueue(self, item):
        # This method adds an item to the queue
        
        if self.data[self.tail] != None:
            err = "Queue overflow, could not add item"
            print(err)
            return
            
        self.data[self.tail] = item
        if self.tail == self.max - 1: # wraparound case
            self.tail = 0 
        else:
            self.tail += 1
        
    def dequeue(self):
        if self.data[self.head] == None:
            err = "Queue underflow, could not dequeue item"
            print(err)
            return None
        else:
            el = self.data[self.head]
            self.data[self.head] = None
            if self.head == self.max -1:
                self.head = 0
            else:
                self.head += 1
            return el

## Linked Lists
Lists which are arranged in an order: The order is determined by pointers <br>
Below we create a doubly linked list


In [289]:
class Doubly_linked_list():
    def __init__(self , head = None):
        # This initializes a doubly linked list - its head argument defaults to None, which represents
        # an empty linked list
        self.head = head
        self.next_key = 0
        
    def search(self , k):
        # this function searches a linked list for an element with the key, k
        x = self.head
        while x != None and x.key != k:
            x = x.next
            return x
            
            
    
    def insert(self, element):
        # This function inserts a new element as the new head
        element.next = self.head   # set the previous head as its sucessor
        if self.head != None: 
            self.head.prev = element   # set the element as the previous head's predecessor
        self.head = element        # replace the previous head
        if element.key == None:
            element.key = self.next_key  # update the elements' key
            self.next_key += 1           # update the sequential key
        
    def delete(self, x):
        # The procedure LIST-DELETE removes an element x from a linked list L. Itmust
        # be given a pointer to x, and it then “splices” x out of the list by updating pointers.
        # If we wish to delete an element with a given key, we must first call LIST-SEARCH
        # to retrieve a pointer to the element.
        if x.prev != None:
            x.prev.next = x.next
        else:                          # if x is the head
            self.head = x.next
            
        if x.next != None:
            x.next.prev = x.prev
            
        # at this point, x is no longer in the linked list
            
class ll_item():
    def __init__(self , successor = None,  predecessor = None , key = None):
        self.next = successor
        self.prev = predecessor
        self.key = key

## Representing Rooted Trees